### ISSUE TITLE
Bug in Level 15

### ISSUE THREAD

**Issue by EtiamSpooky** [euclidthegame/euclidthegame.iOS#11]
I successfully created a circle inscribed in the triangle, but the game is not registering the level as complete.  In fact, when I created the circle, the progress bar dropped from 2/3 full to 1/3 full.  I've tried several methods and they've all had the same result. This is one of these instances.
![image](https://cloud.githubusercontent.com/assets/14010760/9539892/4ae02f00-4d26-11e5-800a-a701fdab58f4.jpg)

**Comment by kasperpeulen** [comment]
Thanks for your report!

Could you try to move around point A,B or C (with the point tool) and see if the solution still appears to be correct ? Did you construct K with the perpendicular tool ?

**Comment by EtiamSpooky** [comment]
Whoops, my bad.  I moved around the points and saw my mistake, sorry about that!
